# Generated by Django 2.2.7 on 2019-12-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191220_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
