# Generated by Django 2.2.7 on 2019-12-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191220_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
